packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  dtrace-provider: true
  msgpackr-extract: false
  prisma: true
  unrs-resolver: false
