services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '${POSTGRES_PORT:-5435}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-acc}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-acc}
      POSTGRES_DB: ${POSTGRES_DB:-acc}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-acc} -d ${POSTGRES_DB:-acc}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6380}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vvk.bhatt93@gmail.com
      PGADMIN_DEFAULT_PASSWORD: '0000'
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
